# Generated by Django 3.1.7 on 2021-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_image',
            field=models.BinaryField(blank=True, default=0),
        ),
    ]
