# Generated by Django 3.1.7 on 2021-04-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_detail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
