# Generated by Django 3.1.7 on 2021-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0002_auto_20210428_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refundable',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
