# Generated by Django 3.1.7 on 2021-05-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0002_remove_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
