# Generated by Django 3.1.7 on 2021-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0002_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
