# Generated by Django 3.1.7 on 2021-04-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0002_auto_20210429_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keyfeature',
        ),
    ]
