# Generated by Django 3.1.7 on 2021-05-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0003_auto_20210501_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Alternate_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='category_size',
            field=models.CharField(blank=True, default='no size', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
