# Generated by Django 3.1.7 on 2021-05-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0003_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
